### ISSUE TITLE
rsconnect_board should handle username updates

### ISSUE THREAD

**Issue by colearendt** [rstudio/pins-r#594]
After migrating authentication providers and changing usernames, we noted the following:

There is a users-cache.yml file that seems to cache usernames. This is a problem because usernames are mutable in Connect and everything we saw suggests that pins will break over such a username change.

There are two core problems:
- the key that a user's code refers to may break over a username change. I don't see a clear way around this one, unless we allow putting in the user's GUID or some other unique / immutable identifier. i.e. if someone wanted to 
- the cache for pins will keep failing even if a user has fixed their code. This is something we should be able to address in the package. We resolved this by removing the offending name in the users cache. (I.e. locally pins were only available at the old name. using the new name would throw an error that such a pin does not exist)

We should think through the behavior of username mutability and how best to allow for this behavior.

**Comment by juliasilge** [comment]
In #667 we changed these caches over to use environments (instead of files on disk). This means that:

- caches will not persist between sessions
- caches will only get into a broken state if a big change is made with the server _while_ a user is working with pins from R
- caches can be fixed by restarting R
- the first time functions are called they will be slow, but subsequent calls will have the same benefits of caching as we had originally

Thanks again for the report! 🙌

**Comment by kmasiello** [comment]
elegant solution! nice job! 🎉
