### ISSUE TITLE
[EEXIST] Error While Attempting To Read In pins Data

### ISSUE THREAD

**Issue by rmccombie** [rstudio/pins-r#598]
While attempting to read in pins data, the following error is received:
```
> data_ed <- pin_read(board = board_rsconnect(), name = "et18378/data_ed_dt")
Connecting to RSC 2021.09.0 at <https://server_name>
Error: [EEXIST] Failed to copy '/tmp/RtmpJvpYRv/file33931451cd351' to '/home/et18378/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/0102056a-79ba-4c51-b81c-f386b6204d9e/203/data.txt': file already exists
```
Directory listing:
```
ls -la /home/et18378/.cache/pins/rsc-e62371cfd77db754024f9c5ed3556a73/0102056a-79ba-4c51-b81c-f386b6204d9e/203/
total 20
drwxr-xr-x+ 2 et18378 domain users 4096 Jan 27 09:56 .
drwxr-xr-x+ 4 et18378 domain users 4096 Jan 27 09:56 ..
-r--r--r--+ 1 et18378 domain users  187 Jan 27 09:56 data.txt
```

(Ticket ref: 70914)

**Comment by juliasilge** [comment]
In #667 we changed the Connect content cache over to use environments (instead of files on disk). This means that:

- caches will not persist between sessions
- caches will only get into a broken state like this if a big change is made with the server _while_ a user is working with pins from R
- caches can be fixed by restarting R
- the first time functions are called they will be slow, but subsequent calls will have the same benefits of caching as we had originally

Thanks again for the report! 🙌 For now, the user will need to install from GitHub to have these improvements but we will do a release soon.
