### ISSUE TITLE
Assignment of non-standard cache folder

### ISSUE THREAD

**Issue by jd4ds** [rstudio/pins-r#747]
Hey everybody, 
we have been using this wonderful package for a long time in our team and since we moved to Posit Workbench we are wondering how to use a shared cache on the Workbench server for pins.
In the documentation of the package and in the source code I could not find any hints that the location where the caching takes place can be customized.
However, for us it would be important to be able to use a shared cache for our pins for performance reasons (cache only needs to be built once and is then available to everyone on the server) and for disk space reasons (pins duplicates in the respective user folders just take up a large amount of disk space).

Is there any possibility or is it planned (soon) to enable this or am I missing something?

Thanks and best regards,
Janis

**Comment by juliasilge** [comment]
The default behavior is for the cache to be at a location like this:

``` r
server <- pins:::rsc_server(auth = "envvar")
pins:::board_cache_path(paste0("connect-", rlang::hash(server$url)))
#> ~/Library/Caches/pins/connect-31a399613ac85efda77ffe6ff20c105a
```

<sup>Created on 2023-06-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The only piece that goes in here is the server URL so I imagine that _value_ would be the same for all users on a Workbench server. They are going into your own home directories, though, because users have separate caches via `rappdirs::user_cache_dir()`.

Is there a directory or cache anywhere on your Workbench server that already is available to all your users? Let's say it is at `/Library/Caches/Shared/ `. Then everyone could do something like `b <- board_connect(cache = "/Library/Caches/Shared/")` and you would all use the same cache. As of today, everyone would need to specify that via the argument every time they create their board object, but I would be happy to fix up the environment variables that pins uses so it could be set via environment variable on the server as a whole.

What do you think about that? Does your server already have a directory like that available?

**Comment by juliasilge** [comment]
Gotcha! If you want to do this right now, you can use the env variable `R_USER_CACHE_DIR` (this works today with the version of pins on CRAN and will continue to work, but _does_ change the cache location for more than just pins so you might not want to do it right now):

``` r
withr::local_envvar(list("R_USER_CACHE_DIR" = "~/Desktop"))
server <- pins:::rsc_server(auth = "envvar")
pins::board_cache_path(paste0("connect-", rlang::hash(server$url)))
#> ~/Desktop/pins/connect-31a399613ac85efda77ffe6ff20c105a
```

<sup>Created on 2023-06-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I added some more documentation on this in #748, as well as a new env var `PINS_CACHE_PATH` that will work similarly (notice no "pins" added to the path):

``` r
withr::local_envvar(list("PINS_CACHE_PATH" = "~/Desktop"))
server <- pins:::rsc_server(auth = "envvar")
pins::board_cache_path(paste0("connect-", rlang::hash(server$url)))
#> ~/Desktop/connect-31a399613ac85efda77ffe6ff20c105a
```

<sup>Created on 2023-06-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jd4ds** [comment]
Excellent, I think that is exactly what we need!

**Comment by juliasilge** [comment]
Glad to hear this will work for your use case! You can install the new version of pins from GitHub now via `pak::pak("rstudio/pins-r")` (or devtools) and start using the new `PINS_CACHE_DIR` environment variable. There is some [new documentation available](https://pins.rstudio.com/dev/reference/board_cache_path.html), and this will go to CRAN with the next release.

Let us know if you have further questions! 🙌
