### ISSUE TITLE
Steps towards Data Version Control for data / modelling sources - idea / feature request

### ISSUE THREAD

**Issue by iandarbeynhiu** [rstudio/pins-r#766]
Hi,

I would like to suggest a feature I've begun to implement by wrapping the pin reading and writing functions in a broader function but could potentially be implemented directly in pins to support comprehensive version control.

For each pin read via the wrapper function a named list is added to (or created on the first read) which captures the pin name, the board path and the version.

For each pin written by the wrapper function that named list is then added as metadata. Along with this I've also included steps to check if the script has been saved and if a commit is needed to potentially reject the pin write (with the script name and commit details also added to the metadata at writing).

The end result for any pin write using my wrapper function is a pin with the source data pin name/s, the board the source data came from and the version of the pin used, along with the script name and associated git details.

While the script and git elements may be considered much less generalisable (reliance on RStudio and git) I think there's some merit to an internal data item which could be optionally populated as pins are read and optionally populated in to the metadata on a pin write.

At the moment my metadata list is returned and updated in the global environment on each pin read but this may be more beneficial as an internal object in the pins package.

I can share the code for my two wrapper functions when I get back to my work laptop on Monday.

**Comment by juliasilge** [comment]
Happy to take a look at some specifics when you get a chance!

**Comment by juliasilge** [comment]
Thanks for sharing this! This is definitely along the lines of [our advice for storing custom metadata with pins](https://pins.rstudio.com/articles/customize-pins-metadata.html). Since this is mostly about metadata and not a specific kind of board, this is functionality that we want to make possible in a flexible way, but not provide really specific functions for in pins itself. I can see folks writing functions like this in internal R packages at their company or for their own use, for sure.

I like the idea of suggesting these kinds of metadata options for folks (filename, package versions, git SHA, etc). Let's update that metadata vignette with some "real world" examples of metadata to be stored.

**Comment by iandarbeynhiu** [comment]
Yes the aim of these is to be incorporated in to an internal R package.
I read that metadata vignette and decided to see if I could trace data sources from input to output and store everything that "made" the output in it's metadata. Initially focused on the data (i.e. the pin reads) but then realised a string of text is a string of text so should really store the script and git commit stuff.
Goal internally will be to write the 2 dependencies to two database tables once we are happy with the core concept and have all the variables we want to capture.

Happy to contribute to a vignette.
