### ISSUE TITLE
Test pins with latest version of paws.common 0.6.0

### ISSUE THREAD

**Issue by DyfanJones** [rstudio/pins-r#778]
Hi all,

I am in the process in releasing the latest version of `paws.common 0.6.0` https://github.com/paws-r/paws/issues/657. `paws.common 0.6.0` comes with a new xml parser that has increased performance: https://github.com/paws-r/paws/pull/621. However I am going around all paws dependent packages to ensure the new xml parser doesn't break any existing code.

Is it possible to run your existing tests with the latest version of `paws.common 0.6.0`? If not please let me know how to set up my environment so that I can test these changes on your behalf.

To install paws.common 0.6.0 you can use r-universe:

```r
install.packages('paws.common', repos = 'https://paws-r.r-universe.dev')
```

**Comment by juliasilge** [comment]
Great news about the new parser and yep, I am happy to do this! We typically use [revdepcheck](https://github.com/r-lib/revdepcheck) for this kind of task, but the situation is a little bit trickier here because the AWS tests only actually run (really read/write to S3) if you have [specific env vars set and a specific bucket](https://github.com/rstudio/pins-r/blob/b962bdbc53b5d4fdf55d0570e52c075f36503894/R/board_s3.R#L130).

**Comment by juliasilge** [comment]
I tested locally and in #779 and both look good to go (specifically [see the `check-boards` action](https://github.com/rstudio/pins-r/actions/runs/6053510724/job/16429163370?pr=779)); you can consider pins all set. ✅

**Comment by DyfanJones** [comment]
@juliasilge thanks for the testing. I will close this ticket :)
