### ISSUE TITLE
Error in cache file 

### ISSUE THREAD

**Issue by lemuelemos** [rstudio/pins-r#785]
![image](https://github.com/rstudio/pins-r/assets/17839354/2afcb715-08d2-4f42-b7ed-5b5dcb8ecbb7)

I use a board folder and share this folder with a cloud app. When a try to read in my notebook i face this error. 

My session info:

![image](https://github.com/rstudio/pins-r/assets/17839354/5bdc91f4-09df-4cf0-b7f9-26e84a8ea3f7)

**Comment by juliasilge** [comment]
So sorry to hear you are having trouble @lemuelemos!

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. Thanks! 🙌

**Comment by juliasilge** [comment]
Let us know if you have further problems!
