### ISSUE TITLE
Error when deleting last version of a pin

### ISSUE THREAD

**Issue by MichalLauer** [rstudio/pins-r#837]
Hello,

Thanks for this great package!

I am uploading custom files to a local board. However, there is an error thrown whenever I

1) create a board and a pin,
2) upload a file using `pin_upload()`,
3) remove that pin, and
4) try to upload a new one.

Here is a custom reprex that replicates this issue:

``` r
library(pins)
#> Warning: package 'pins' was built under R version 4.3.3

# Prepare data
write.csv(mtcars, file = "mtcars.csv")

# Create temp board and first upload
board <- board_temp(versioned = TRUE)
pin_upload(board = board, paths = "mtcars.csv", name = "data")
#> Creating new version '20240824T203215Z-cd94d'

# Delete just created pin
latest_version <- pin_versions(board = board, name = "data")$version
pin_version_delete(board = board, name = "data", version = latest_version)

# Upload new data
pin_upload(board = board, paths = "mtcars.csv", name = "data")
#> Error in versions$version[[1]]: subscript out of bounds
```

I think the issue happens within the `version_setup()` on line 162:

https://github.com/rstudio/pins-r/blob/2edcccbb5b73e61c5fdaaedf4a8e22251e38df35/R/pin_versions.R#L160-L171

because in that state, the board exists without any pins (and hence without any versions).

Could a simple fix be just a check in the if statement?

``` r
if (pin_exists(board, name) & length(versions) > 0) {
  ...
}
```

If so, happy to do a PR :) Thanks!

**Comment by juliasilge** [comment]
Thanks so much for this report! I believe you have diagnosed the problem correctly, yes.

I don't think we can do `if (pin_exists(board, name) & length(versions) > 0)` because we can't do `pin_versions()` until we know the pin exists, but we can add an additional check inside the if statement, or maybe add a new little helper which _could_ be called in the if statement after the currently existing part:

```r
pin_version_exists <- function(board, name) {
  versions <- pin_versions(board, name)
  length(versions) > 0
}
```

We would welcome a PR with one of these fixes if you are interested! 🙌
